apiVersion: apps/v1
kind: Deployment
metadata:
  name: fewv-client
  labels:
    app: fewv-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fewv-client
  template:
    metadata:
      labels:
        app: fewv-client
    spec:
      containers:
        - name: fewv-client
          image: ashwinsai22/fewv-client:latest
          ports:
            - containerPort: 80