apiVersion: v1
kind: Service
metadata:
  name: fewv-client
  labels:
    app: fewv-client
spec:
  type: NodePort
  selector:
    app: fewv-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080