apiVersion: v1
kind: Service
metadata:
  name: fewv-client
  namespace: fewv
spec:
  type: NodePort
  selector:
    app: fewv-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080