apiVersion: v1
kind: Service
metadata:
  name: fewv-client-lb
  namespace: fewv
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: fewv-client
  ports:
    - port: 80
      targetPort: 80