apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fewv-ingress
  namespace: fewv
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fewv.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fewv-client
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fewv-server
                port:
                  number: 3000