apiVersion: v1
kind: Service
metadata:
  name: fewv-server
  namespace: fewv
spec:
  type: NodePort
  selector:
    app: fewv-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30081