apiVersion: apps/v1
kind: Deployment
metadata:
  name: fewv-server
  namespace: fewv
  labels:
    app: fewv-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fewv-server
  template:
    metadata:
      labels:
        app: fewv-server
    spec:
      containers:
        - name: fewv-server
          image: ashwinsai22/fewv-server:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: fewv-server-secrets
