apiVersion: v1
kind: Service
metadata:
  name: fewv-server
  namespace: fewv
  labels:
    app: fewv-server
spec:
  type: NodePort
  selector:
    app: fewv-server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001